### ISSUE TITLE
Cannot read property 'post' of undefined

### ISSUE THREAD

**Issue by freezegr** [detectlanguage/detectlanguage-node#3]
(node:8080) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'post' of undefined
at C:\Users\freeze\desktop\better-discord-tts\node_modules\detectlanguage\lib\index.js:1:671

how I can fix it?

**Comment by laurynas** [comment]
Could you please provide code sample how to reproduce this issue? Which node version you are using?

**Comment by freezegr** [comment]
i fix it
